version: '2'
services:
    studioconsole-couchbase:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        ports:
            - 8091:8091
            - 8092:8092
            - 8093:8093
            - 11210:11210
        environment:
            - TYPE=MASTER
            - BUCKET=StudioConsole
    studioconsole-couchbase-node:
        build:
            context: .
            dockerfile: couchbase/Couchbase.Dockerfile
        environment:
            - TYPE=WORKER
            - BUCKET=StudioConsole
            - COUCHBASE_MASTER=studioconsole-couchbase
            - AUTO_REBALANCE=false
